# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "10.x"

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    displayName: cache yarn packages

  - script: |
      yarn install
    displayName: "yarn install"

  - script: |
      yarn run validate
    displayName: "yarn validate"

  - script: |
      CONTEXT=PIPELINE BUILD_NUMBER=$(Build.BuildNumber) COMMIT_ID=$(Build.SourceVersion) yarn run build
    displayName: "yarn build"

  # Disabled for forks because: "By default with GitHub repositories, secret variables associated with your pipeline aren't made available to pull request builds of forks"
  #   https://docs.microsoft.com/fr-fr/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#contributions-from-forks
  - script: |
      yarn run deploy:preview --auth $(NETLIFY_AUTH_TOKEN)
    displayName: "deploy preview"
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['System.PullRequest.IsFork'], 'True'))

  - script: |
      yarn run deploy:prod --auth $(NETLIFY_AUTH_TOKEN)
    displayName: "deploy prod"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: "junit.xml"

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura # or JaCoCo
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/cobertura-coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
